[[LibStdCxx]]
arch = "x86_64"
git-tree-sha1 = "d1fd8b7b6a26aaa13e4fd714030afb886386742e"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibStdCxx.download]]
    sha256 = "1ae9c4c0e3ae509ad4532832b04a43faf56bc48e6125f520f0d03511ca65a02d"
    url = "https://github.com/JuliaBinaryWrappers/LibStdCxx_jll.jl/releases/download/LibStdCxx-v12.1.0+1/LibStdCxx.v12.1.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
