[[LibStdCxx]]
arch = "x86_64"
git-tree-sha1 = "cccb23108c71bcfe59d1e3453a7bac447a469acd"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibStdCxx.download]]
    sha256 = "3601b0e03efac44318e2e4df649a38b198a68e040d4c3da4a2dc5f370437b7d1"
    url = "https://github.com/JuliaBinaryWrappers/LibStdCxx_jll.jl/releases/download/LibStdCxx-v12.1.0+0/LibStdCxx.v12.1.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
