# Autogenerated wrapper script for LibStdCxx_jll for x86_64-linux-gnu-sanitize+memory
JLLWrappers.@generate_wrapper_header("LibStdCxx")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
